import { MissionTask, DisasterSector, INITIAL_SECTORS } from '@swarmos/shared';

export function createInitialTasks(): MissionTask[] {
  return [
    {
      id: 'task-map-01',
      missionId: 'mission-alpha-7',
      type: 'MAPPING',
      title: 'Orthophoto Mapping Sector A-01',
      description: 'Capture high-resolution 3D point cloud & aerial map of the Financial District North rubble field.',
      sectorCode: 'SEC-A01',
      priority: 'HIGH',
      location: { lat: 37.7788, lng: -122.4150, alt: 70 },
      targetRadiusMeters: 120,
      requiredCapability: 'MAPPER',
      status: 'IN_PROGRESS',
      assignedDroneId: 'drone-01',
      progress: 68,
      deadlineSeconds: 420,
      createdAt: Date.now() - 300000,
      updatedAt: Date.now(),
    },
    {
      id: 'task-search-02',
      missionId: 'mission-alpha-7',
      type: 'SEARCH',
      title: 'Structural Void Search Sector B-14',
      description: 'Optical sweep for trapped survivors along Civic Center collapsed building perimeter.',
      sectorCode: 'SEC-B14',
      priority: 'CRITICAL',
      location: { lat: 37.7740, lng: -122.4115, alt: 50 },
      targetRadiusMeters: 90,
      requiredCapability: 'SEARCH',
      status: 'IN_PROGRESS',
      assignedDroneId: 'drone-02',
      progress: 64,
      deadlineSeconds: 300,
      createdAt: Date.now() - 400000,
      updatedAt: Date.now(),
    },
    {
      id: 'task-relay-03',
      missionId: 'mission-alpha-7',
      type: 'COMM_RELAY',
      title: 'Mesh Network Anchor Sector CORE',
      description: 'Maintain persistent 5.8GHz relay link between forward units and Mobile Command Unit.',
      sectorCode: 'SEC-CORE',
      priority: 'HIGH',
      location: { lat: 37.7738, lng: -122.4175, alt: 110 },
      targetRadiusMeters: 300,
      requiredCapability: 'RELAY',
      status: 'IN_PROGRESS',
      assignedDroneId: 'drone-03',
      progress: 88,
      deadlineSeconds: 900,
      createdAt: Date.now() - 600000,
      updatedAt: Date.now(),
    },
    {
      id: 'task-thermal-04',
      missionId: 'mission-alpha-7',
      type: 'THERMAL_SCAN',
      title: 'Thermal Anomaly Scan Sector C-08',
      description: 'FLIR radiometric scan to detect heat signatures in West Market Commercial sector.',
      sectorCode: 'SEC-C08',
      priority: 'HIGH',
      location: { lat: 37.7795, lng: -122.4240, alt: 45 },
      targetRadiusMeters: 100,
      requiredCapability: 'THERMAL',
      status: 'IN_PROGRESS',
      assignedDroneId: 'drone-04',
      progress: 52,
      deadlineSeconds: 360,
      createdAt: Date.now() - 250000,
      updatedAt: Date.now(),
    },
    {
      id: 'task-pend-05',
      missionId: 'mission-alpha-7',
      type: 'SEARCH',
      title: 'Corridor Sweep Sector D-02',
      description: 'Secondary search along residential corridor for stranded civilians.',
      sectorCode: 'SEC-D02',
      priority: 'MEDIUM',
      location: { lat: 37.7710, lng: -122.4200, alt: 55 },
      targetRadiusMeters: 150,
      requiredCapability: 'SEARCH',
      status: 'PENDING',
      assignedDroneId: null,
      progress: 0,
      deadlineSeconds: 600,
      createdAt: Date.now() - 100000,
      updatedAt: Date.now(),
    },
  ];
}

export function createInitialSectors(): DisasterSector[] {
  return JSON.parse(JSON.stringify(INITIAL_SECTORS));
}
