import { DroneTelemetry, Mission, DisasterSector, GeoPoint } from './types';

// Epicenter of the Simulated Urban Earthquake (Downtown District)
export const SIMULATION_CENTER: GeoPoint = {
  lat: 37.7749,
  lng: -122.4194,
  alt: 0,
};

export const COMMAND_CENTER_LOCATION: GeoPoint = {
  lat: 37.7715,
  lng: -122.4245,
  alt: 5,
};

export const DEFAULT_ALGORITHM_WEIGHTS = {
  priorityWeight: 35,
  distanceWeight: 25,
  batteryWeight: 20,
  capabilityWeight: 20,
  commQualityWeight: 10,
  workloadPenaltyWeight: 15,
};

export const SAFETY_PARAMETERS = {
  horizontalSafetyRadiusMeters: 25,
  verticalSafetySeparationMeters: 15,
  criticalCollisionDistanceMeters: 12,
  criticalBatteryThresholdPercent: 20,
  warningBatteryThresholdPercent: 35,
  commSignalLossThresholdDbm: -88,
  commWarningThresholdDbm: -78,
  maxDroneSpeedMps: 18,
  surveyAltitudeMeters: 65,
  relayAltitudeMeters: 110,
  thermalAltitudeMeters: 45,
};

export const INITIAL_DRONES: DroneTelemetry[] = [
  {
    id: 'drone-01',
    callsign: 'SPECTER-1',
    name: 'Drone 01 — Mapper',
    role: 'MAPPER',
    status: 'EN_ROUTE',
    battery: 92,
    speed: 12.4,
    altitude: 70,
    heading: 45,
    position: { lat: 37.7765, lng: -122.4172, alt: 70 },
    targetPosition: { lat: 37.7788, lng: -122.4150, alt: 70 },
    homePosition: COMMAND_CENTER_LOCATION,
    waypoints: [
      { id: 'wp-1', lat: 37.7765, lng: -122.4172, alt: 70, action: 'SCAN' },
      { id: 'wp-2', lat: 37.7788, lng: -122.4150, alt: 70, action: 'SCAN' },
      { id: 'wp-3', lat: 37.7810, lng: -122.4130, alt: 70, action: 'SCAN' },
    ],
    currentTaskId: 'task-map-01',
    health: {
      status: 'OPTIMAL',
      temperatureC: 34.2,
      motorRpm: 5400,
      vibrationScore: 12,
      signalStrengthDbm: -56,
      packetLossPercent: 0.1,
      lastHeartbeat: Date.now(),
    },
    sensors: {
      hasOpticalCamera: true,
      hasThermalSensor: false,
      hasLidar: true,
      hasRelayAntenna: false,
      slamConfidence: 96,
      slamLandmarks: 480,
      slamDriftMeters: 0.12,
      opticalFps: 60,
    },
    slamMode: 'HYBRID',
    assignedSector: 'SEC-A01',
    flightTimeSeconds: 520,
    distanceCoveredMeters: 2840,
    tasksCompletedCount: 3,
    confidenceScore: 98,
    color: '#06b6d4', // Cyan
  },
  {
    id: 'drone-02',
    callsign: 'SEEKER-2',
    name: 'Drone 02 — Search',
    role: 'SEARCH',
    status: 'SCANNING',
    battery: 73,
    speed: 9.8,
    altitude: 50,
    heading: 135,
    position: { lat: 37.7752, lng: -122.4140, alt: 50 },
    targetPosition: { lat: 37.7740, lng: -122.4115, alt: 50 },
    homePosition: COMMAND_CENTER_LOCATION,
    waypoints: [
      { id: 'wp-4', lat: 37.7752, lng: -122.4140, alt: 50, action: 'SCAN' },
      { id: 'wp-5', lat: 37.7740, lng: -122.4115, alt: 50, action: 'SCAN' },
      { id: 'wp-6', lat: 37.7725, lng: -122.4100, alt: 50, action: 'SCAN' },
    ],
    currentTaskId: 'task-search-02',
    health: {
      status: 'NORMAL',
      temperatureC: 38.5,
      motorRpm: 5250,
      vibrationScore: 18,
      signalStrengthDbm: -62,
      packetLossPercent: 0.4,
      lastHeartbeat: Date.now(),
    },
    sensors: {
      hasOpticalCamera: true,
      hasThermalSensor: false,
      hasLidar: true,
      hasRelayAntenna: false,
      slamConfidence: 91,
      slamLandmarks: 420,
      slamDriftMeters: 0.28,
      opticalFps: 60,
    },
    slamMode: 'GPS',
    assignedSector: 'SEC-B14',
    flightTimeSeconds: 780,
    distanceCoveredMeters: 4120,
    tasksCompletedCount: 5,
    confidenceScore: 94,
    color: '#3b82f6', // Blue
  },
  {
    id: 'drone-03',
    callsign: 'NEXUS-3',
    name: 'Drone 03 — Relay',
    role: 'RELAY',
    status: 'RELAYING',
    battery: 88,
    speed: 3.2,
    altitude: 110,
    heading: 270,
    position: { lat: 37.7735, lng: -122.4180, alt: 110 },
    targetPosition: { lat: 37.7738, lng: -122.4175, alt: 110 },
    homePosition: COMMAND_CENTER_LOCATION,
    waypoints: [
      { id: 'wp-7', lat: 37.7735, lng: -122.4180, alt: 110, action: 'RELAY' },
    ],
    currentTaskId: 'task-relay-03',
    health: {
      status: 'OPTIMAL',
      temperatureC: 32.1,
      motorRpm: 4800,
      vibrationScore: 8,
      signalStrengthDbm: -48,
      packetLossPercent: 0.05,
      lastHeartbeat: Date.now(),
    },
    sensors: {
      hasOpticalCamera: true,
      hasThermalSensor: false,
      hasLidar: false,
      hasRelayAntenna: true,
      slamConfidence: 99,
      slamLandmarks: 310,
      slamDriftMeters: 0.08,
      opticalFps: 30,
    },
    slamMode: 'HYBRID',
    assignedSector: 'SEC-CORE',
    flightTimeSeconds: 1150,
    distanceCoveredMeters: 1820,
    tasksCompletedCount: 1,
    confidenceScore: 99,
    color: '#10b981', // Emerald
  },
  {
    id: 'drone-04',
    callsign: 'PYRO-4',
    name: 'Drone 04 — Thermal',
    role: 'THERMAL',
    status: 'SCANNING',
    battery: 81,
    speed: 8.5,
    altitude: 45,
    heading: 315,
    position: { lat: 37.7780, lng: -122.4220, alt: 45 },
    targetPosition: { lat: 37.7795, lng: -122.4240, alt: 45 },
    homePosition: COMMAND_CENTER_LOCATION,
    waypoints: [
      { id: 'wp-8', lat: 37.7780, lng: -122.4220, alt: 45, action: 'THERMAL_SWEEP' },
      { id: 'wp-9', lat: 37.7795, lng: -122.4240, alt: 45, action: 'THERMAL_SWEEP' },
    ],
    currentTaskId: 'task-thermal-04',
    health: {
      status: 'OPTIMAL',
      temperatureC: 41.0,
      motorRpm: 5550,
      vibrationScore: 15,
      signalStrengthDbm: -58,
      packetLossPercent: 0.2,
      lastHeartbeat: Date.now(),
    },
    sensors: {
      hasOpticalCamera: true,
      hasThermalSensor: true,
      hasLidar: true,
      hasRelayAntenna: false,
      slamConfidence: 93,
      slamLandmarks: 510,
      slamDriftMeters: 0.18,
      opticalFps: 60,
    },
    slamMode: 'SLAM',
    assignedSector: 'SEC-C08',
    flightTimeSeconds: 640,
    distanceCoveredMeters: 3390,
    tasksCompletedCount: 4,
    confidenceScore: 96,
    color: '#f59e0b', // Amber
  },
];

export const INITIAL_SECTORS: DisasterSector[] = [
  {
    code: 'SEC-A01',
    name: 'Financial District North',
    bounds: [
      { lat: 37.779, lng: -122.420, alt: 0 },
      { lat: 37.779, lng: -122.414, alt: 0 },
      { lat: 37.776, lng: -122.414, alt: 0 },
      { lat: 37.776, lng: -122.420, alt: 0 },
    ],
    center: { lat: 37.7775, lng: -122.4170, alt: 0 },
    priority: 'HIGH',
    explorationPercent: 82,
    hazardLevel: 'MODERATE',
    detectedSurvivorsCount: 2,
    assignedDroneId: 'drone-01',
  },
  {
    code: 'SEC-B14',
    name: 'Civic Center Collapse Zone',
    bounds: [
      { lat: 37.776, lng: -122.414, alt: 0 },
      { lat: 37.776, lng: -122.408, alt: 0 },
      { lat: 37.773, lng: -122.408, alt: 0 },
      { lat: 37.773, lng: -122.414, alt: 0 },
    ],
    center: { lat: 37.7745, lng: -122.4110, alt: 0 },
    priority: 'CRITICAL',
    explorationPercent: 64,
    hazardLevel: 'SEVERE',
    detectedSurvivorsCount: 3,
    assignedDroneId: 'drone-02',
  },
  {
    code: 'SEC-C08',
    name: 'West Market Commercial Sector',
    bounds: [
      { lat: 37.780, lng: -122.426, alt: 0 },
      { lat: 37.780, lng: -122.420, alt: 0 },
      { lat: 37.776, lng: -122.420, alt: 0 },
      { lat: 37.776, lng: -122.426, alt: 0 },
    ],
    center: { lat: 37.7780, lng: -122.4230, alt: 0 },
    priority: 'HIGH',
    explorationPercent: 48,
    hazardLevel: 'MODERATE',
    detectedSurvivorsCount: 1,
    assignedDroneId: 'drone-04',
  },
  {
    code: 'SEC-D02',
    name: 'South Residential Corridor',
    bounds: [
      { lat: 37.773, lng: -122.424, alt: 0 },
      { lat: 37.773, lng: -122.416, alt: 0 },
      { lat: 37.769, lng: -122.416, alt: 0 },
      { lat: 37.769, lng: -122.424, alt: 0 },
    ],
    center: { lat: 37.7710, lng: -122.4200, alt: 0 },
    priority: 'MEDIUM',
    explorationPercent: 32,
    hazardLevel: 'LOW',
    detectedSurvivorsCount: 0,
    assignedDroneId: null,
  },
];

export const INITIAL_MISSION: Mission = {
  id: 'mission-alpha-7',
  name: 'OPERATION METRO RESCUE',
  scenarioName: 'Urban Earthquake Magnitude 7.2',
  description: 'Multi-agent autonomous search, 3D aerial mapping, survivor identification, and comms mesh stabilization in high-density rubble zone.',
  status: 'ACTIVE',
  searchStrategy: 'ADAPTIVE_HEATMAP',
  centerLocation: SIMULATION_CENTER,
  radiusMeters: 1400,
  totalSectors: 8,
  exploredSectors: 4,
  survivorsFound: 6,
  hazardsDetected: 14,
  activeDronesCount: 4,
  coveragePercent: 57.4,
  startTime: Date.now() - 14 * 60 * 1000,
  elapsedSeconds: 840,
  estimatedRemainingSeconds: 960,
};
